{% set name = "panel-splitjs" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/panel_splitjs-{{ version }}.tar.gz
  sha256: 84df543cf1a58d2691cc64f9c109ce0e874b20403deb3ab4c5dbf0d958e88f74

build:
  skip: True # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - hatchling
    - hatch-vcs
    - panel >=1.8.0
    - nodejs 24.*
    - esbuild 0.25.4
    - packaging
    - pip
  run:
    - python
    - panel >=1.8.0
    - bokeh >=3.8.0
    - packaging

test:
  imports:
    - panel_splitjs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/panel-extensions/panel-splitjs
  summary: A responsive, draggable split panel component for Panel applications, powered by split.js.
  dev_url: https://github.com/panel-extensions/panel-splitjs
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  dev_url: https://github.com/panel-extensions/panel-splitjs
  doc_url: https://github.com/panel-extensions/panel-splitjs

extra:
  recipe-maintainers:
    - maximlt
    - philippjfr
