{% set name = "panel-splitjs" %}
{% set version = "0.3.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/13/7b/2561475e74528bbe544508fe36578d6790f546fa221d5ff412b2ab4e3f97/panel_splitjs-{{ version }}.tar.gz
  sha256: 20ca66163debeba9e51b763406d69c41555ec37f04edda1c36133574e048f16b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - panel >=1.8.0
    - nodejs >=22.*
    - esbuild
    - packaging
    - pip
  run:
    - python >={{ python_min }}
    - panel >=1.8.0
    - bokeh >=3.8.0
    - packaging

test:
  imports:
    - panel_splitjs
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/panel-extensions/panel-splitjs
  summary: A responsive, draggable split panel component for Panel applications, powered by split.js.
  dev_url: https://github.com/panel-extensions/panel-splitjs
  license: BSD-3-Clause
  license_file: LICENSE.txt


extra:
  recipe-maintainers:
    - maximlt
    - philippjfr
