{% set name = "panel-splitjs" %}
{% set version = "0.3.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/panel_splitjs-{{ version }}.tar.gz
  sha256: e5038f7cf37b12b72ef52ac44ff53fd8a72bd111a0ffe28afc1b9fac3450604a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - panel >=1.8.0
    - nodejs >=22.*
    - esbuild
    - packaging
    - pip
  run:
    - python >={{ python_min }}
    - panel >=1.8.0
    - bokeh >=3.8.0
    - packaging

test:
  imports:
    - panel_splitjs
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/panel-extensions/panel-splitjs
  summary: A responsive, draggable split panel component for Panel applications, powered by split.js.
  dev_url: https://github.com/panel-extensions/panel-splitjs
  license: BSD-3-Clause
  license_file: LICENSE.txt


extra:
  recipe-maintainers:
    - maximlt
    - philippjfr
